version: '2'
services:
  db:
    container_name: customdb-4
    image: 'customdb:latest'
    ports: 
        - 9034:3306
    volumes:
        - db-one:/var/lib/mysql
volumes:
  db-one:
    external: true